#Project
project_name: ner-medical

#Data
data:
  dataset_name: bigbio/bc5cdr
  dataset_config: bc5cdr_bigbio_ner
  max_length: 512


model:
  name: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext
  num_labels: 5
  dropout: 0.1


training:
  epochs: 20
  batch_size: 16
  lr: 2e-5
  weight_decay: 0.01
  warmup_steps: 500
  seed: 42
  fp16: True

mlflow:
  experiment_name: ner-medical
  tracking_uri: logs/mlflow
  run_name: baseline

paths:
  output_dirs: models/
  logs_dir: logs/
  metrics_dir: metrics/

